apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-processor-gitops
  namespace: argocd # Asumiendo que ArgoCD está instalado en este namespace
spec:
  project: default
  source:
    # 🚨 REEMPLAZA con la URL de tu repositorio de Git público o privado
    repoURL: 'https://github.com'
    targetRevision: HEAD
    path: k8s # La carpeta dentro del repositorio donde están los archivos yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true     # Borra recursos en K8s si los borras en Git
      selfHeal: true
