apiVersion: v1
kind: Service
metadata:
  name: payment-processor-service
  namespace: monitoring
  labels:
    app: payment-processor
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: payment-processor
---
apiVersion: ://coreos.com
kind: ServiceMonitor
metadata:
  name: payment-processor-monitor
  namespace: monitoring
  labels:
    # Esta etiqueta DEBE coincidir con el selector del operador de Prometheus de tu Helm chart
    release: monitoring 
spec:
  selector:
    matchLabels:
      app: payment-processor
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
